# Part of OpenG2P. See LICENSE file for full copyright and licensing details.
{
    "name": "OpenG2P Country Config: ATI",
    "category": "G2P",
    "version": "17.0.1.2.0",
    "sequence": 1,
    "author": "OpenG2P",
    "website": "https://openg2p.org",
    "license": "Other OSI approved licence",
    "development_status": "Alpha",
    "depends": ["g2p_social_registry", "storage_file"],
    "external_dependencies": {"python": ["ethiopian-date"]},
    "data": [
        "data/region.xml",
        "data/zone.xml",
        "data/genders.xml",
        "security/ir.model.access.csv",
        "views/social_registry_menu.xml",
        "views/livestock.xml",
        "views/commodity.xml",
        "views/cooperations.xml",
        "views/region.xml",
        "views/zone.xml",
        "views/woreda.xml",
        "views/kebele.xml",
        "views/lang.xml",
        "views/illness.xml",
        "views/water_sources.xml",
        "views/hh_income_type.xml",
        "views/res_partner.xml",
        "views/crop_category.xml",
        "views/crop.xml",
        "views/land_info.xml",
    ],
    "assets": {"web.assets_backend": []},
    "demo": [],
    "images": [],
    "application": True,
    "installable": True,
    "auto_install": False,
}
